changed algo of height counting
BMSTU-Schedule/bmstu-schedule-photo pull request #2
Opened 2019-08-29 12:49 UTC by hackallcode

2019-08-29 13:01 UTC, gabolaev requested changes

2019-08-29 13:01 UTC, gabolaev commented on etc/transformations/remove_weeknum.js
> -function () {
не надо разделять weeknum с header-ом. Это два отдельных смысловых процесса удаления.

2019-08-29 13:01 UTC, gabolaev commented on etc/transformations/physical_culture.js
> +    let spans = document.getElementsByTagName('span');
phantomjs не поддерживает ES6

2019-08-29 14:45 UTC, hackallcode commented on etc/transformations/physical_culture.js
> +    let spans = document.getElementsByTagName('span');
Ай, исправлю

2019-08-29 14:45 UTC, hackallcode commented on etc/transformations/remove_weeknum.js
> -function () {
Я не то чтобы сливал, я просто добавил туда еще немного логики, однако окей, разделю

2019-08-29 20:45 UTC, trubitsyn requested changes

2019-08-29 20:45 UTC, trubitsyn commented on analyzer/analyser.go
> +	// doubleColWidth = 35.72
Если не нужно, то стоит удалить.

2019-08-29 20:45 UTC, trubitsyn commented on analyzer/analyser.go
> +			res++
`length+1+wordLen` - стоит вынести в отдельную переменную

2019-08-29 20:45 UTC, trubitsyn commented on analyzer/analyser.go
> +	res := 1
Что такое `res`? Сразу не понятно.

2019-08-29 20:45 UTC, trubitsyn commented on analyzer/analyser.go
> +	return CountHeight(strings.NewReader(data))
Возможно, `Reader` стоит закрывать, но не уверен. @gabolaev?

2019-08-29 20:45 UTC, trubitsyn commented on analyzer/analyser.go
> +	nilString      = "NIL"
Возможно, существует другой способ реализации логики без этой "заглушки"?

2019-08-29 20:45 UTC, trubitsyn commented on analyzer/analyser.go
> +			length += 1 + wordLen
`+=` вместе с `+` выглядит не очень

2019-08-29 20:45 UTC, trubitsyn commented on analyzer/analyser.go
> +			var trHeight float64
Нужен ли здесь float или можно округлить до целого без существенных потерь?

2019-08-29 20:45 UTC, trubitsyn commented on analyzer/analyser.go
> +	doc.Find("div.col-md-6.hidden-xs tbody").Each(func(tableNum int, tbody *goquery.Selection) {
Селекторы (`div...`) стоит вынести в отдельные перемкенные, чтобы было понятно, за какой блок на странице они отвечают.

2019-08-29 20:45 UTC, trubitsyn commented on analyzer/analyser.go
> +		if tableNum%2 == 0 {
Сразу не понятно, что обозначает это условие в контексте логики функции. Стоит завести переменную под это.

2019-08-29 20:48 UTC, gabolaev commented on analyzer/analyser.go
> +	return CountHeight(strings.NewReader(data))
https://golang.org/pkg/strings/#Reader
нет, не надо

2019-08-29 21:01 UTC, ed-asriyan commented on analyzer/analyser.go
> +			length += 1 + wordLen
да норм же

2019-08-29 21:03 UTC, ed-asriyan commented on analyzer/analyser.go
> +		if tableNum%2 == 0 {
или комментарий просто

2019-08-29 21:08 UTC, trubitsyn commented on analyzer/analyser.go
> +			length += 1 + wordLen
Часть кода `length+1` все равно дублируется, и непонятно зачем там инкремент.

2019-08-29 21:09 UTC, ed-asriyan commented on analyzer/analyser.go
> +	res := 1
результат функции -> кол-во строк

только зачем флоат? если уж надо использовать значение как флоат, то лучше уж после вызова функции приводить типы

2019-08-29 21:10 UTC, gabolaev requested changes

2019-08-29 21:10 UTC, gabolaev commented on analyzer/analyser.go
> +				if tdNum == 1 {
switch case жиес

2019-08-29 21:10 UTC, gabolaev commented on analyzer/analyser.go
> +				trHeight = math.Max(rowsCount(leftText, singleColWidth), rowsCount(rightText, singleColWidth))
если это какое-то промежуточное значение, может стоит его как-то иначе по смыслу назвать, а то одна и та  же переменная заполняется в 2 операции по непонятной логике.

2019-08-29 21:10 UTC, ed-asriyan commented on analyzer/analyser.go
> +			res++
да и тут норм кмк. комменты бы, а то на самом деле не очевидно по коду. можно прям из текста PR в код накопировать

2019-08-29 21:11 UTC, ed-asriyan commented on analyzer/analyser.go
> +		if tableNum%2 == 0 {
комменты бы, а то на самом деле не очевидно по коду. можно прям из текста PR в код накопировать

2019-08-29 21:12 UTC, ed-asriyan commented on analyzer/analyser.go
> +			length += 1 + wordLen
> Часть кода `length+1` все равно дублируется, и непонятно зачем там инкремент.

ну ок, убедил

2019-08-29 21:16 UTC, gabolaev requested changes

2019-08-29 21:16 UTC, gabolaev commented on analyzer/analyser.go
> +			leftText := nilString
а вот эта завязка на эту странную константу NIL не избыточна? Разве нельзя достичь того же эффекта через пустую строку?

2019-08-29 21:23 UTC, ed-asriyan commented on analyzer/analyser.go
> +				if tdNum == 1 {
да у нас и так в других местах 💩, че придрался то :D но если не влом поправить было бы неплохо

2019-08-30 09:34 UTC, hackallcode commented on analyzer/analyser.go
> +			leftText := nilString
Пустую строку нельзя, потому что иногда там значение - пустая строка и это далеко не пустой значение

2019-08-30 09:36 UTC, hackallcode commented on analyzer/analyser.go
> +	doc.Find("div.col-md-6.hidden-xs tbody").Each(func(tableNum int, tbody *goquery.Selection) {
Теперь там есть комментарии, это еще понятнее

2019-08-30 09:36 UTC, hackallcode commented on analyzer/analyser.go
> +			var trHeight float64
Пикселей 30 можно так потерять, так что нет

2019-08-31 21:14 UTC, trubitsyn approved these changes

2019-09-01 10:15 UTC, gabolaev approved these changes

2019-09-01 15:28 UTC, ed-asriyan approved these changes

2019-09-02 07:15 UTC, gabolaev commented
катнул на dev твою ветку и вот
![image](https://user-images.githubusercontent.com/10693243/64096516-8d28ce80-cd6a-11e9-8007-63b115bb3c97.png)

2019-09-02 10:39 UTC, gabolaev requested changes
неверно режет, нужно поправить

снизу там еще один предмет, он не влез
![image](https://user-images.githubusercontent.com/10693243/64109050-29f96500-cd87-11e9-85bf-074e4b64b746.png)

2019-09-03 09:37 UTC, gabolaev commented
что-то как-то криво
![image](https://user-images.githubusercontent.com/10693243/64162232-9dfb4200-ce47-11e9-9e2b-e055c0d75856.png)

2019-09-03 21:23 UTC, ed-asriyan requested changes
ага, криво режется

2019-09-05 20:24 UTC, closed without merging